version: "3.1"
services:
  springapp:
   image: purvansh14/spring-boot-mongo:BUILD_TAG
   restart: always
   container_name: springbootcontainer
   environment:
   - MONGO_DB_HOSTNAME=springdbmongo
   - MONGO_DB_USERNAME=devdb
   - MONGO_DB_PASSWORD=bhavani@123
   ports:
   - 9980:8080
   working_dir: /opt/app
   depends_on:
     - springdbmongo
   deploy:
     replicas: 2
     update_config:
       parallelism: 1
       delay: 20s
     restart_policy:
       condition: on-failure
       delay: 10s
       max_attempts: 5
   networks:
   - springappnetwork1
  springdbmongo:
    image: mongo
    container_name: springdbcontainer
    environment:
    - MONGO_INITDB_ROOT_USERNAME= devdb
    - MONGO_INITDB_ROOT_PASSWORD=bhavani@123
    volumes:
    - springvolume:/data/db
    networks:
    - springappnetwork1
volumes:
  springvolume:
    driver: local
networks:
  springappnetwork1:
    driver: bridge
