apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapps
  template:
    metadata:
      name: springpod
      labels:
        app: springapps
    spec:
      containers:
      - name: springcontainer
        image: purvansh14/spring-boot-app:BUILDTAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
        - name: MONGO_DB_HOSTNAME
          value: mongosvc

---


apiVersion: v1
kind: Service
metadata:
  name: springsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: springapps
  ports:
  - port: 80
    targetPort: 8080


---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongors
  namespace: test-ns
spec:
 selector:
   matchLabels:
     app: mongo
 template:
   metadata:
     name: mongopod
     labels:
       app: mongo
   spec:
     containers:
     - image: mongo
       name: mongocontainer
       ports:
       - containerPort: 27017
       resources:
         requests:
            cpu: 250m
            memory: 256Mi
         limits:
           cpu: 500m
           memory: 512Mi
       env:
       - name: MONGO_INITDB_ROOT_USERNAME
         value: devdb
       - name: MONGO_INITDB_ROOT_PASSWORD
         value: devdb@123


---

apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
